version: '3.4'
services:
  restarter:
    image: docker:cli
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]
    command: [ "/bin/sh", "-c", "while true; do sleep 43200; docker restart kafka-ui; done" ]
    restart: always
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    restart: always
    ports:
      - 80:8080
    extra_hosts:
      - "kafka1.cluster.com:130.1.1.51"
      - "kafka2.cluster.com:130.1.1.52"
      - "kafka3.cluster.com:130.1.1.53"
    environment:
      #### Secure kafka connected to cluster.com domain TLS + KERBEROS
      KAFKA_CLUSTERS_0_NAME: secure-Kafka-cluster
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: GSSAPI
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: com.sun.security.auth.module.Krb5LoginModule required useKeyTab=true storeKey=true keyTab="/etc/kafkaui/cluster/daviduser.keytab" principal="daviduser1@CLUSTER.COM";
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_KERBEROS_SERVICE_NAME: "kafka"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1.cluster.com:9093,kafka2.cluster.com:9093,kafka3.cluster.com:9093
      KAFKA_CLUSTERS_0_SSL_TRUSTSTORELOCATION: /etc/kafkaui/cluster/my.truststore
      KAFKA_CLUSTERS_0_SSL_TRUSTSTOREPASSWORD: zaq123
      KAFKA_CLUSTERS_0_METRICS_PORT: 8080
      KAFKA_CLUSTERS_0_METRICS_TYPE: PROMETHEUS
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: '' # DISABLE COMMON NAME VERIFICATION
      
#### General configuration
#      ## If you wish to enable the configuration from the UI enable this value
#      #DYNAMIC_CONFIG_ENABLED: true
    volumes:
      - ./cluster/my.truststore:/etc/kafkaui/cluster/my.truststore:U
      - ./cluster/daviduser-keytab:/etc/kafkaui/cluster/daviduser-keytab:U
      - ./krb5.conf:/etc/krb5.conf:U
