version: '3.4'
services:
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    extra_hosts:
      - "kafka1-nonesecure:130.1.1.1"
      - "kafka2-nonesecure:130.1.1.2"
      - "kafka3-nonesecure:130.1.1.3"
      - "kafka4-nonesecure:130.1.1.4"
      - "kafka5-nonesecure:130.1.1.5"
      - "kafka6-nonesecure:130.1.1.6"
    environment:
      #### Unsecure kafka cluster configuration ####
      KAFKA_CLUSTERS_0_NAME: unsecure-kafka-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1-nonesecure:9092
      #DYNAMIC_CONFIG_ENABLED: true
