version: '3.4'
services:
  restarter:
    image: docker:cli
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]
    command: [ "/bin/sh", "-c", "while true; do sleep 43200; docker restart kafka-ui; done" ]
    restart: always
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    restart: always
    ports:
      - 80:8080
    extra_hosts:
      - "kafka1-nonesecure:130.1.1.1"
      - "kafka1-nonesecure:130.1.1.2"
      - "kafka1-nonesecure:130.1.1.3"
      - "kafka1-nonesecure:130.1.1.4"
      - "kafka1-nonesecure:130.1.1.5"
      - "kafka1-nonesecure:130.1.1.6"
      - "kafka1.cluster.com:130.1.1.51"
      - "kafka2.cluster.com:130.1.1.52"
      - "kafka3.cluster.com:130.1.1.53"
      - "kafka1-tls.cluster.com:130.1.1.54"
      - "kafka2-tls.cluster.com:130.1.1.55"
      - "kafka3-tls.cluster.com:130.1.1.56"

    environment:
      #### Unsecure kafka
      KAFKA_CLUSTERS_0_NAME: unsecure-kafka-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1-nonesecure:9092

      #### Secure kafka connected to cluster.com domain TLS + KERBEROS
      KAFKA_CLUSTERS_1_NAME: secure-Kafka-cluster
      KAFKA_CLUSTERS_1_PROPERTIES_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_CLUSTERS_1_PROPERTIES_SASL_MECHANISM: GSSAPI
      KAFKA_CLUSTERS_1_PROPERTIES_SASL_JAAS_CONFIG: com.sun.security.auth.module.Krb5LoginModule required useKeyTab=true storeKey=true keyTab="/etc/kafkaui/cluster/daviduser.keytab" principal="daviduser1@CLUSTER.COM";
      KAFKA_CLUSTERS_1_PROPERTIES_SASL_KERBEROS_SERVICE_NAME: "kafka"
      KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: kafka1.cluster.com:9093,kafka2.cluster.com:9093,kafka3.cluster.com:9093
      KAFKA_CLUSTERS_1_SSL_TRUSTSTORELOCATION: /etc/kafkaui/cluster/my.truststore
      KAFKA_CLUSTERS_1_SSL_TRUSTSTOREPASSWORD: zaq123
      KAFKA_CLUSTERS_1_METRICS_PORT: 8080
      KAFKA_CLUSTERS_1_METRICS_TYPE: PROMETHEUS
      KAFKA_CLUSTERS_1_PROPERTIES_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: '' # DISABLE COMMON NAME VERIFICATION

      #### Secure kafka connected to cluster.com domain TLS only
      KAFKA_CLUSTERS_2_NAME: tls-Kafka-cluster
      KAFKA_CLUSTERS_2_PROPERTIES_SECURITY_PROTOCOL: SSL
      KAFKA_CLUSTERS_2_PROPERTIES_SASL_MECHANISM: GSSAPI
      KAFKA_CLUSTERS_2_BOOTSTRAPSERVERS: kafka1-tls.cluster.com:9093,kafka2-tls.cluster.com:9093,kafka3-tls.cluster.com:9093
      KAFKA_CLUSTERS_2_SSL_TRUSTSTORELOCATION: /etc/kafkaui/cluster-tls/tls.truststore
      KAFKA_CLUSTERS_2_SSL_TRUSTSTOREPASSWORD: zaq123
      KAFKA_CLUSTERS_2_METRICS_PORT: 8080
      KAFKA_CLUSTERS_2_METRICS_TYPE: PROMETHEUS
      KAFKA_CLUSTERS_2_PROPERTIES_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: '' # DISABLE COMMON NAME VERIFICATION
#### General configuration
#      ## If you wish to enable the configuration from the UI enable this value
#      #DYNAMIC_CONFIG_ENABLED: true
    volumes:
      - ./cluster/my.truststore:/etc/kafkaui/cluster/my.truststore:U
      - ./cluster/daviduser-keytab:/etc/kafkaui/cluster/daviduser-keytab:U
      - ./cluster-tls/tls.truststore:/etc/kafkaui/cluster-tls/tls.truststore:U
      - ./krb5.conf:/etc/krb5.conf:U
